spring:
  application:
    name: licensingservice
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true
    stream:
      bindings:
        input:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
#        inboundOrgChanges:
#          destination: orgChangeTopic
#          content-type: application/json
#          group: licensingGroup
#          consumer:
#            resetOffsets: false
        binder:
          zkNodes: localhost
          brokers: localhost

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

