spring:
  application:
    name: zuul-service
  profiles:
    active:
      default # 设置环境: dev, test, prod
  cloud:
    config:
      enabled: true #允许通过 config server 获取配置信息

server:
  port: 5555

#Setting logging levels
#logging:
#    level:
#      com.netflix: WARN
#      org.springframework.web: WARN
#      com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
#
#  debug:
#    request: true
# routes from config
#zuul:
##  prefix:  /api
#  routes:
#    organizationservice: /organization/**
#    licensingservice: /licensing/**
#    auth-service: /auth-service/**