server:
  port: 8761 #Default port is 8761

eureka:
  client:
    registerWithEureka: false #自己是注册中心，不需要注册 registerWithEureka
    fetchRegistry: false # 自己是注册中心，不需要获取注册信息 fetchRegistry
    serviceUrl:
      defaultZone: http://localhost:8761
  server:
    waitTimeInMsWhenSyncEmpty: 0 #同步为空时的等待时间

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
